### ISSUE TITLE
Copyright and Licenses for the code

### ISSUE THREAD

**Issue by GO5IT** [coronalabs/GettingStarted01#1]
Hello,

Quick question. The getting started tutorial is great, but I am just wondering what copyright and licenses are applied for the code (and materials used in the code). I would like to modify and reuse it, but I am not sure what I can do about it.

Can I use it for any purposes, or are there any restrictions? It would be highly appreciated if the code on Github shows the license information. Thank you!

**Comment by Shchvova** [comment]
All our sample code is MIT licensed. Feel free to use it.

**Comment by GO5IT** [comment]
Ok, thank you for your information.
Just one little request.
Could you quickly choose MIT license logo for this repository (to display it explicitly)?
That encourages people (like me) more to use the code (and feel much safer).
Many thanks!
